spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

mail:
  host: smtp.gmail.com
  port: ${MAIL_PORT:465}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        ssl:
          enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE:true}
        starttls:
          enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:false}
        connectiontimeout: 15000
        timeout: 15000
        writetimeout: 15000

  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  verification:
    # This now dynamically points to your frontend or backend URL
    url: ${APP_BASE_URL}/api/v1/auth/verify?token=